version: '3.8'

services:
  postgres:
    image: postgres
    container_name: eticket-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5433:5432"


  mongo:
    image: mongo
    container_name: eticket-mongo
    ports:
      - "27017:27017"


  rabbitmq:
    image: rabbitmq:3-management
    container_name: eticket-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: 123456
    ports:
      - "5672:5672"
      - "15672:15672"