spring:
  application:
    name: eticket-gw
  cloud:
    gateway:
      routes:
        - id: eticket-service
          uri: lb://ETICKET-SERVICE
          predicates:
            - Path=/api/v1/trips/**
        - id: eticket-service
          uri: lb://ETICKET-SERVICE
          predicates:
            - Path=/api/v1/tickets/**
        - id: eticket-user-service
          uri: lb://ETICKET-USER-SERVICE
          predicates:
            - Path=/api/v1/users/**
        - id: eticket-user-service
          uri: lb://ETICKET-USER-SERVICE
          predicates:
            - Path=/api/v1/roles/**
        - id: eticket-user-service
          uri: lb://ETICKET-USER-SERVICE
          predicates:
            - Path=/api/v1/individual-users/**
        - id: eticket-user-service
          uri: lb://ETICKET-USER-SERVICE
          predicates:
            - Path=/api/v1/company-users/**
        - id: eticket-user-service
          uri: lb://ETICKET-USER-SERVICE
          predicates:
            - Path=/api/v1/admin-users/**
        - id: notification-service
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/api/v1/email-templates/**
        - id: notification-service
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/api/v1/emails/**

server:
  port: 9090