spring:
  application:
    name: eticket-gw
  cloud:
    gateway:
      routes:
        - id: eticket-service
          uri: lb://ETICKET-SERVICE
          predicates:
            - Path=/api/v1/trips/**
        - id: eticket-service
          uri: lb://ETICKET-SERVICE
          predicates:
            - Path=/api/v1/tickets/**
        - id: eticket-user-service
          uri: lb://ETICKET-USER-SERVICE
          predicates:
            - Path=/api/v1/users/**
        - id: eticket-user-service
          uri: lb://ETICKET-USER-SERVICE
          predicates:
            - Path=/api/v1/roles/**
        - id: eticket-user-service
          uri: lb://ETICKET-USER-SERVICE
          predicates:
            - Path=/api/v1/individual-users/**
        - id: eticket-user-service
          uri: lb://ETICKET-USER-SERVICE
          predicates:
            - Path=/api/v1/company-users/**
        - id: eticket-user-service
          uri: lb://ETICKET-USER-SERVICE
          predicates:
            - Path=/api/v1/admin-users/**
        - id: notification-service
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/api/v1/email-templates/**
        - id: notification-service
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/api/v1/emails/**
        - id: eticket-index-service
          uri: lb://ETICKET-INDEX-SERVICE
          predicates:
            - Path=/api/v1/documents/**
        - id: eticket-search-service
          uri: lb://ETICKET-SEARCH-SERVICE
          predicates:
            - Path=/api/v1/search/**
        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/api/v1/payments/**


server:
  port: 9090